trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    source venv/bin/activate
    python -m unittest discover
  displayName: 'Run tests'

- task: CopyFiles@2
  inputs:
    contents: |
      **/*
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files to artifact staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish artifacts'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'UdacityDS - 72'
    appName: 'webappProjectUdacity'
    package: '$(Build.ArtifactStagingDirectory)/drop'
  displayName: 'Deploy to Azure App Service'
